services:
  - type: web
    name: mental-health-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"

  - type: web
    name: mental-health-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run front.py --server.port 8501 --server.address 0.0.0.0"
